[versions]
agp = "8.7.2"
kotlin = "2.1.0"
# ksp
ksp = "2.1.0-1.0.29"
#AndroidX y Core
coreKtx = "1.17.0"
appcompat = "1.7.1"
activity = "1.9.3"
material3 = "1.4.0"
# Lifecycle
lifecycleRuntimeKtx = "2.8.7"
# Lifecycle Components
#lifecycle-viewmodel-ktx = "2.8.7"
#lifecycle-livedata-ktx = "2.8.7"
# Compose
composeBom = "2024.11.00"
activityCompose = "1.9.3"
#Material
materialIconsExtended = "1.7.5"
foundationLayout = "1.7.5"
# Navigation (Nav 3 es experimental, si falla sugiero volver a 2.8.4)
nav3 = "1.0.0-alpha01"
material3AdaptiveNav3 = "1.0.0-alpha01"
nav3-runtime = "1.0.0-beta01"
# koin
koin-bom = "4.0.0"
# Room
room = "2.6.1"
# datastore
datastoreCore = "1.1.1"
# retrofit
retrofit = "2.11.0"
converterKotlinxSerialization = "2.11.0"
# serialization
<<<<<<< HEAD
kotlinSerialization = "2.1.0"
kotlinxSerializationJson = "1.7.3"
kotlinxSerializationCore = "1.7.3"
# Testing
junit = "4.13.2"
junitVersion = "1.2.0"
espressoCore = "3.6.1"

=======
kotlinxSerializationJson = "1.10.0-RC"
converterKotlinxSerialization = "3.0.0"
kotlinSerialization = "2.2.21"
kotlinxSerializationCore = "1.9.0"
material3AdaptiveNav3 = "1.3.0-alpha06"
material3 = "1.4.0"
>>>>>>> origin/modificaciones

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-material3-adaptive-navigation3 = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation3", version.ref = "material3AdaptiveNav3" }
nav3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3" }
nav3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3" }
lifecycle-viewmodel-nav3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "lifecycleRuntimeKtx" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinxSerializationCore" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-compose = { module = "io.insert-koin:koin-compose" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout", version.ref = "foundationLayout" }
androidx-datastore-core = { group = "androidx.datastore", name = "datastore-core", version.ref = "datastoreCore" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastoreCore" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
converter-kotlinx-serialization = { module = "com.squareup.retrofit2:converter-kotlinx-serialization", version.ref = "converterKotlinxSerialization" }
<<<<<<< HEAD
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
=======
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
>>>>>>> origin/modificaciones

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin"}
google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }